version: '2'
services:
  ui:
    networks:
      harbor-clair:
        aliases:
          - harbor-ui
  jobservice:
    networks:
      - harbor-clair
  registry:
    networks:
      - harbor-clair
  postgresql:
    image: goharbor/harbor-db:v1.6.0
    container_name: clair-db
    restart: always
    volumes:
      - /data/database:/var/lib/postgresql/data:z
    env_file:
      - ./common/config/clair/postgres_env
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "postgresql"
    networks:
      harbor-clair:
        aliases:
          - harbor-db
  clair:
    networks:
      - harbor-clair
    container_name: clair
    image: goharbor/clair-photon:v2.0.5-v1.6.0
    restart: always
    cpu_quota: 50000
    depends_on:
      - postgresql
    volumes:
      - ./common/config/clair/config.yaml:/etc/clair/config.yaml:z
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "clair"
    env_file:
      ./common/config/clair/clair_env
networks:
  harbor-clair:
    external: false
